[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lizard-delta"
version = "0.2.0"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
lizard-base = "lizard_delta.lizard_base:main"
lizard-to-code-quality = "lizard_delta.lizard_to_code_quality:main"

[tool.hatch.build.targets.wheel]
packages = ["src/lizard_delta"]
